/**
 * Mirrored Handprint — Whole-Form Cluster Element Module (Round 36 Candidate)
 * ===========================================================================
 *
 * A rotated keyboard footprint supplies glyph-local geometry for dense hand
 * clusters (4- and 5-note groups at the same onset and hand); surrounding
 * fixed-3 staff is unchanged.
 *
 * Geometry:
 * - Anchor is the lowest sounding pitch p0, with explicit absolute solf numeral
 *   and register placement coinciding with the anchor's displayed staff height.
 * - Local y[i] = -u * (p[i] - p0), increasing pitch upward (u = 2.4 pt/semitone).
 * - Local x[i] = +a for odd p[i], -a for even p[i] (a = 3.0 pt).
 * - Central axis is the onset axis.
 * - Odd-semitone transposition reflects internal form left/right;
 *   even-semitone transposition preserves it, generated by ONE mirrored geometry routine.
 * - Landmarks connected in ascending order as a single narrow, smoothly joined
 *   calligraphic body with small outward shoulders/lobes at sounding landmarks.
 * - Base numeral integrated at the origin; other numerals absent.
 * - Clearly owned duration attachments: uniform rhythm shared at summit;
 *   differing releases visibly attached to relevant landmark shoulders.
 * - Exact inverse pitch decoding recoverable from anchor + landmark geometry.
 */

import { Hand, QuantizedNote } from '../../../model/types';
import { getDuodecimalDigit } from '../../types';
import {
  ResolvedJankoLayoutOptions,
  ResolvedJankoTokens,
} from '../types';
import { f } from './style';
import { digitBaselineOffset } from './notehead';
import type { PositionedJankoNote } from '../engine';

// ---------------------------------------------------------------------------
// Published Testable Geometry Constants
// ---------------------------------------------------------------------------

/** Pitch interval scale along glyph: 2.4 pt per semitone (28.8 pt per octave). */
export const HANDPRINT_PITCH_UNIT_U = 2.4;
export const HANDPRINT_U = HANDPRINT_PITCH_UNIT_U;

/** Horizontal displacement from central onset axis: 3.0 pt (total row span 6.0 pt). */
export const HANDPRINT_ROW_DISPLACEMENT_A = 3.0;
export const HANDPRINT_A = HANDPRINT_ROW_DISPLACEMENT_A;

/** Outward shoulder/lobe horizontal reach from landmark center (pt). */
export const HANDPRINT_LOBE_WIDTH = 2.0;

/** Outward shoulder/lobe vertical half-height (pt). */
export const HANDPRINT_LOBE_HALF_HEIGHT = 1.1;

/** Narrow connecting calligraphic body half-width (pt). */
export const HANDPRINT_BODY_HALF_WIDTH = 0.8;

/** Origin base numeral knockout half-width (pt). */
export const HANDPRINT_ORIGIN_KNOCKOUT_WX = 2.4;

/** Origin base numeral knockout half-height (pt). */
export const HANDPRINT_ORIGIN_KNOCKOUT_HY = 3.2;

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

/** Sounding landmark of one constituent pitch in a handprint cluster. */
export interface JankoHandprintLandmark {
  /** Sounding linear pitch: 12 * octave + pitchClass. */
  pitch: number;
  /** Pitch class (0..11). */
  pitchClass: number;
  /** Parity: 0 for even, 1 for odd. */
  parity: 0 | 1;
  /** Local horizontal offset from onset axis (pt): +a for odd, -a for even. */
  localX: number;
  /** Local vertical offset from anchor staff height (pt): -u * (pitch - p0). */
  localY: number;
  /** Page absolute X (pt): onsetX + localX. */
  x: number;
  /** Page absolute Y (pt): anchorStaffY + localY. */
  y: number;
  /** Duration (ticks) of this constituent note. */
  durationTicks: number;
  /** Source note ID. */
  noteId: string;
}

/** Distinct duration release subset within a handprint cluster. */
export interface JankoHandprintDurationSubset {
  durationTicks: number;
  noteIds: string[];
  /** Landmark this duration attachment owns and attaches to. */
  landmark: JankoHandprintLandmark;
}

/** One candidate handprint cluster representing a dense 4/5-note chord. */
export interface JankoHandprintCluster {
  id: string;
  startTick: number;
  hand: Hand;
  /** Sounding linear pitch of the anchor (lowest note). */
  baseLin: number;
  /** Anchor pitch class (0..11). */
  basePitchClass: number;
  /** Displayed staff height of the anchor note (page pt). */
  anchorStaffY: number;
  /** Central onset axis column on page (pt). */
  onsetX: number;
  /** Sounding landmarks in ascending pitch order. */
  landmarks: JankoHandprintLandmark[];
  /** Set of all source note IDs in this cluster. */
  allNoteIds: Set<string>;
  /** Positioned notes belonging to this cluster. */
  notes: PositionedJankoNote[];
  /** Bounding box of all ink: [minX, minY, maxX, maxY] in page pt. */
  inkBox: [number, number, number, number];
  /** Distinct duration release subsets. */
  durationSubsets: JankoHandprintDurationSubset[];
  /** True if all constituent notes share the exact same duration. */
  isUniformRhythm: boolean;
  /** The uniform duration in ticks (if uniform). */
  uniformDurationTicks?: number;
}

// ---------------------------------------------------------------------------
// Forward Geometry & Clustering
// ---------------------------------------------------------------------------

/** Get sounding linear pitch from a note or positioned note. */
export function getSoundingPitch(note: QuantizedNote | PositionedJankoNote): number {
  const q = 'note' in note ? note.note : note;
  const pc = ((q.pitch.pitchClass % 12) + 12) % 12;
  return q.pitch.octave * 12 + pc;
}

/**
 * Group positioned notes into handprint clusters.
 * Focus: same-hand, same-onset 4- and 5-note groups (>= 4 notes).
 * 2/3-note groups stay literal for this experiment.
 */
export function groupHandprintClusters(
  notes: readonly PositionedJankoNote[],
  u: number = HANDPRINT_PITCH_UNIT_U,
  a: number = HANDPRINT_ROW_DISPLACEMENT_A
): {
  clusters: JankoHandprintCluster[];
  handprintNoteIds: Set<string>;
} {
  // Group notes by startTick and hand
  const byOnset = new Map<string, PositionedJankoNote[]>();
  for (const n of notes) {
    const k = `${n.note.startTick}_${n.note.hand}`;
    const list = byOnset.get(k);
    if (list) {
      list.push(n);
    } else {
      byOnset.set(k, [n]);
    }
  }

  const clusters: JankoHandprintCluster[] = [];
  const handprintNoteIds = new Set<string>();

  for (const group of byOnset.values()) {
    if (group.length < 4) continue; // 2/3-note groups stay literal

    // Sort constituent notes strictly ascending by sounding linear pitch
    const sorted = [...group].sort((n1, n2) => getSoundingPitch(n1) - getSoundingPitch(n2));
    const anchorNote = sorted[0];
    const baseLin = getSoundingPitch(anchorNote);
    const basePitchClass = ((baseLin % 12) + 12) % 12;
    const anchorStaffY = anchorNote.y;

    // The onset axis is the nominal unshifted column X of the onset
    // In Janko layout, anchorNote.x sits on the onset column
    const onsetX = Math.min(...group.map((n) => n.x));

    const landmarks: JankoHandprintLandmark[] = sorted.map((n) => {
      const pitch = getSoundingPitch(n);
      const pc = ((pitch % 12) + 12) % 12;
      const parity: 0 | 1 = (pitch % 2 !== 0) ? 1 : 0;
      const localX = parity === 1 ? +a : -a;
      const localY = -u * (pitch - baseLin);
      return {
        pitch,
        pitchClass: pc,
        parity,
        localX,
        localY,
        x: onsetX + localX,
        y: anchorStaffY + localY,
        durationTicks: n.note.durationTicks,
        noteId: n.note.id,
      };
    });

    // Partition by duration ticks
    const durMap = new Map<number, JankoHandprintLandmark[]>();
    for (const lm of landmarks) {
      const list = durMap.get(lm.durationTicks);
      if (list) list.push(lm);
      else durMap.set(lm.durationTicks, [lm]);
    }

    const isUniformRhythm = durMap.size === 1;
    const uniformDurationTicks = isUniformRhythm ? landmarks[0].durationTicks : undefined;

    const durationSubsets: JankoHandprintDurationSubset[] = [];
    for (const [dur, lms] of durMap.entries()) {
      // Owned attachment site: the highest landmark in this duration subset
      const highestLm = lms[lms.length - 1];
      durationSubsets.push({
        durationTicks: dur,
        noteIds: lms.map((l) => l.noteId),
        landmark: highestLm,
      });
    }

    // Sort duration subsets ascending by duration
    durationSubsets.sort((a, b) => a.durationTicks - b.durationTicks);

    // Compute ink bounding box
    let minX = onsetX - a - HANDPRINT_LOBE_WIDTH;
    let maxX = onsetX + a + HANDPRINT_LOBE_WIDTH;
    let minY = landmarks[landmarks.length - 1].y - HANDPRINT_LOBE_HALF_HEIGHT;
    let maxY = anchorStaffY + HANDPRINT_LOBE_HALF_HEIGHT;

    // Account for origin knockout/digit
    minX = Math.min(minX, onsetX - a - HANDPRINT_ORIGIN_KNOCKOUT_WX);
    maxX = Math.max(maxX, onsetX + a + HANDPRINT_ORIGIN_KNOCKOUT_WX);
    minY = Math.min(minY, anchorStaffY - HANDPRINT_ORIGIN_KNOCKOUT_HY);
    maxY = Math.max(maxY, anchorStaffY + HANDPRINT_ORIGIN_KNOCKOUT_HY);

    // Account for duration attachments (approx 6pt outward or 8pt upward)
    if (isUniformRhythm) {
      minY -= 9.0; // Summit duration cue extends upward
    } else {
      maxX += 8.0; // Differing release cues extend outward
      minX -= 4.0;
    }

    const cluster: JankoHandprintCluster = {
      id: `handprint-${anchorNote.note.startTick}-${anchorNote.note.hand}`,
      startTick: anchorNote.note.startTick,
      hand: anchorNote.note.hand,
      baseLin,
      basePitchClass,
      anchorStaffY,
      onsetX,
      landmarks,
      allNoteIds: new Set(group.map((n) => n.note.id)),
      notes: sorted,
      inkBox: [minX, minY, maxX, maxY],
      durationSubsets,
      isUniformRhythm,
      uniformDurationTicks,
    };

    clusters.push(cluster);
    for (const n of group) {
      handprintNoteIds.add(n.note.id);
    }
  }

  return { clusters, handprintNoteIds };
}

// ---------------------------------------------------------------------------
// Calligraphic Body Path Generation
// ---------------------------------------------------------------------------

/**
 * Construct the SVG path data for the single narrow, smoothly joined calligraphic body.
 * Connects landmarks in ascending order with small outward shoulders/lobes at sounding landmarks.
 *
 * This routine is purely mirrored: odd transposition reflects x left/right;
 * even transposition preserves geometry identically.
 */
export function renderHandprintBodyPath(
  landmarks: readonly JankoHandprintLandmark[],
  wLobe: number = HANDPRINT_LOBE_WIDTH,
  hLobe: number = HANDPRINT_LOBE_HALF_HEIGHT,
  wBody: number = HANDPRINT_BODY_HALF_WIDTH
): string {
  if (landmarks.length === 0) return '';
  const n = landmarks.length;

  // Build right-side contour ascending from landmark 0 to n-1
  const rightPoints: Array<{ x: number; y: number; cmd?: string; cp1?: { x: number; y: number }; cp2?: { x: number; y: number } }> = [];

  for (let i = 0; i < n; i++) {
    const lm = landmarks[i];
    const isOdd = lm.parity === 1;

    if (isOdd) {
      // Landmark is on right (+a). Outward shoulder/lobe swells outward to the right (+x)
      const xBase = lm.x + wBody;
      const xApex = lm.x + wLobe;
      const yBot = lm.y + hLobe;
      const yMid = lm.y;
      const yTop = lm.y - hLobe;

      // Start of lobe, curve to apex, curve back to body
      rightPoints.push({ x: xBase, y: yBot, cmd: 'L' });
      rightPoints.push({
        x: xApex,
        y: yMid,
        cmd: 'C',
        cp1: { x: xApex, y: yBot },
        cp2: { x: xApex, y: yMid + 0.3 * hLobe },
      });
      rightPoints.push({
        x: xBase,
        y: yTop,
        cmd: 'C',
        cp1: { x: xApex, y: yMid - 0.3 * hLobe },
        cp2: { x: xApex, y: yTop },
      });
    } else {
      // Landmark is on left (-a). Right side is the inward body boundary
      const xInward = lm.x + wBody;
      rightPoints.push({ x: xInward, y: lm.y, cmd: 'L' });
    }
  }

  // Summit transition: wrap over the top landmark (n - 1)
  const topLm = landmarks[n - 1];
  const summitOver = {
    x: topLm.x,
    y: topLm.y - hLobe - 0.5,
  };

  // Build left-side contour descending from landmark n-1 down to 0
  const leftPoints: Array<{ x: number; y: number; cmd?: string; cp1?: { x: number; y: number }; cp2?: { x: number; y: number } }> = [];

  for (let i = n - 1; i >= 0; i--) {
    const lm = landmarks[i];
    const isEven = lm.parity === 0;

    if (isEven) {
      // Landmark is on left (-a). Outward shoulder/lobe swells outward to the left (-x)
      const xBase = lm.x - wBody;
      const xApex = lm.x - wLobe;
      const yTop = lm.y - hLobe;
      const yMid = lm.y;
      const yBot = lm.y + hLobe;

      leftPoints.push({ x: xBase, y: yTop, cmd: 'L' });
      leftPoints.push({
        x: xApex,
        y: yMid,
        cmd: 'C',
        cp1: { x: xApex, y: yTop },
        cp2: { x: xApex, y: yMid - 0.3 * hLobe },
      });
      leftPoints.push({
        x: xBase,
        y: yBot,
        cmd: 'C',
        cp1: { x: xApex, y: yMid + 0.3 * hLobe },
        cp2: { x: xApex, y: yBot },
      });
    } else {
      // Landmark is on right (+a). Left side is the inward body boundary
      const xInward = lm.x - wBody;
      leftPoints.push({ x: xInward, y: lm.y, cmd: 'L' });
    }
  }

  // Base transition: wrap under the bottom landmark (0)
  const botLm = landmarks[0];
  const baseUnder = {
    x: botLm.x,
    y: botLm.y + hLobe + 0.5,
  };

  // Assemble the closed SVG path string
  const dParts: string[] = [];
  const start = rightPoints[0];
  dParts.push(`M ${f(start.x)} ${f(start.y)}`);

  for (let i = 1; i < rightPoints.length; i++) {
    const pt = rightPoints[i];
    if (pt.cmd === 'C' && pt.cp1 && pt.cp2) {
      dParts.push(`C ${f(pt.cp1.x)} ${f(pt.cp1.y)}, ${f(pt.cp2.x)} ${f(pt.cp2.y)}, ${f(pt.x)} ${f(pt.y)}`);
    } else {
      dParts.push(`L ${f(pt.x)} ${f(pt.y)}`);
    }
  }

  // Over summit
  dParts.push(`Q ${f(summitOver.x)} ${f(summitOver.y)}, ${f(leftPoints[0].x)} ${f(leftPoints[0].y)}`);

  for (let i = 1; i < leftPoints.length; i++) {
    const pt = leftPoints[i];
    if (pt.cmd === 'C' && pt.cp1 && pt.cp2) {
      dParts.push(`C ${f(pt.cp1.x)} ${f(pt.cp1.y)}, ${f(pt.cp2.x)} ${f(pt.cp2.y)}, ${f(pt.x)} ${f(pt.y)}`);
    } else {
      dParts.push(`L ${f(pt.x)} ${f(pt.y)}`);
    }
  }

  // Under base and close
  dParts.push(`Q ${f(baseUnder.x)} ${f(baseUnder.y)}, ${f(start.x)} ${f(start.y)}`);
  dParts.push('Z');

  return dParts.join(' ');
}

// ---------------------------------------------------------------------------
// Duration Attachment Symbols (Existing Vocabulary)
// ---------------------------------------------------------------------------

/**
 * Render standard duration cue mark:
 * - 192 ticks (whole): double open ring
 * - 144 ticks (dotted half): open ring + augmentation dot
 * - 96 ticks (half): single open ring
 * - 48 ticks (quarter): plain vertical stem tick
 * - 24 ticks (eighth): stem tick + flag notch
 */
export function renderHandprintDurationCue(
  x: number,
  y: number,
  durationTicks: number,
  scale: number = 1.0
): string {
  const r = 1.35 * scale;
  const dotR = 0.9 * scale;
  const strokeWidth = 0.65 * scale;
  const parts: string[] = [];

  if (durationTicks >= 192) {
    // Double open ring (whole note)
    parts.push(
      `<circle class="janko-handprint-dur-ring" cx="${f(x)}" cy="${f(y - r - 0.4)}" r="${f(r)}" fill="#FFFFFF" stroke="#111111" stroke-width="${f(strokeWidth)}"/>`
    );
    parts.push(
      `<circle class="janko-handprint-dur-ring" cx="${f(x)}" cy="${f(y + r + 0.4)}" r="${f(r)}" fill="#FFFFFF" stroke="#111111" stroke-width="${f(strokeWidth)}"/>`
    );
  } else if (durationTicks === 144) {
    // Single open ring + augmentation dot (dotted half)
    parts.push(
      `<circle class="janko-handprint-dur-ring" cx="${f(x)}" cy="${f(y)}" r="${f(r)}" fill="#FFFFFF" stroke="#111111" stroke-width="${f(strokeWidth)}"/>`
    );
    parts.push(
      `<circle class="janko-handprint-dur-dot" cx="${f(x + r + dotR + 1.2)}" cy="${f(y)}" r="${f(dotR)}" fill="#111111"/>`
    );
  } else if (durationTicks >= 96) {
    // Single open ring (half note)
    parts.push(
      `<circle class="janko-handprint-dur-ring" cx="${f(x)}" cy="${f(y)}" r="${f(r)}" fill="#FFFFFF" stroke="#111111" stroke-width="${f(strokeWidth)}"/>`
    );
  } else if (durationTicks >= 48) {
    // Plain quarter stem tick
    parts.push(
      `<line class="janko-handprint-dur-stem" x1="${f(x)}" y1="${f(y - 3.5 * scale)}" x2="${f(x)}" y2="${f(y + 3.5 * scale)}" stroke="#111111" stroke-width="${f(0.85 * scale)}"/>`
    );
  } else if (durationTicks >= 24) {
    // Eighth note stem tick + flag
    parts.push(
      `<line class="janko-handprint-dur-stem" x1="${f(x)}" y1="${f(y - 3.5 * scale)}" x2="${f(x)}" y2="${f(y + 3.5 * scale)}" stroke="#111111" stroke-width="${f(0.85 * scale)}"/>`
    );
    parts.push(
      `<line class="janko-handprint-dur-flag" x1="${f(x)}" y1="${f(y - 2.5 * scale)}" x2="${f(x + 2.5 * scale)}" y2="${f(y - 0.8 * scale)}" stroke="#111111" stroke-width="${f(0.75 * scale)}"/>`
    );
  } else {
    // 16th note stem tick + double flag
    parts.push(
      `<line class="janko-handprint-dur-stem" x1="${f(x)}" y1="${f(y - 3.5 * scale)}" x2="${f(x)}" y2="${f(y + 3.5 * scale)}" stroke="#111111" stroke-width="${f(0.85 * scale)}"/>`
    );
    parts.push(
      `<line class="janko-handprint-dur-flag" x1="${f(x)}" y1="${f(y - 2.8 * scale)}" x2="${f(x + 2.5 * scale)}" y2="${f(y - 1.2 * scale)}" stroke="#111111" stroke-width="${f(0.75 * scale)}"/>`
    );
    parts.push(
      `<line class="janko-handprint-dur-flag" x1="${f(x)}" y1="${f(y - 1.2 * scale)}" x2="${f(x + 2.5 * scale)}" y2="${f(y + 0.4 * scale)}" stroke="#111111" stroke-width="${f(0.75 * scale)}"/>`
    );
  }

  return parts.join('');
}

// ---------------------------------------------------------------------------
// SVG Assembly
// ---------------------------------------------------------------------------

/**
 * Render the complete mirrored handprint SVG group for one cluster:
 * 1. Connected calligraphic body `<path class="janko-handprint-body" ...>`
 * 2. Origin base numeral with white knockout and duodecimal digit
 * 3. Clearly owned duration attachments
 */
export function renderHandprintSvg(
  cluster: JankoHandprintCluster,
  tokens: ResolvedJankoTokens
): { svg: string; inkBox: [number, number, number, number] } {
  const parts: string[] = [];
  parts.push(`  <g class="janko-mirrored-handprint" data-cluster-id="${cluster.id}">`);

  // 1. Single connected calligraphic body path
  const bodyPathD = renderHandprintBodyPath(cluster.landmarks);
  parts.push(
    `    <path class="janko-handprint-body" d="${bodyPathD}" fill="#111111" stroke="none"/>`
  );

  // 2. Base numeral integrated at the origin (landmark 0)
  const originLm = cluster.landmarks[0];
  const digit = getDuodecimalDigit(cluster.basePitchClass);
  const baseline = originLm.y + digitBaselineOffset(tokens.digitFontSize);
  const kwx = HANDPRINT_ORIGIN_KNOCKOUT_WX;
  const khy = HANDPRINT_ORIGIN_KNOCKOUT_HY;

  // White knockout behind the base digit
  parts.push(
    `    <rect class="janko-knockout" x="${f(originLm.x - kwx)}" y="${f(originLm.y - khy)}" width="${f(2 * kwx)}" height="${f(2 * khy)}" fill="#FFFFFF"/>`
  );
  // Upright, readable duodecimal digit (never mirrored)
  parts.push(
    `    <text class="janko-digit" x="${f(originLm.x)}" y="${f(baseline)}" font-weight="700" font-size="${tokens.digitFontSize.toFixed(1)}pt" fill="#111111">${digit}</text>`
  );

  // 3. Clearly owned duration attachments
  if (cluster.isUniformRhythm && cluster.uniformDurationTicks !== undefined) {
    // Uniform rhythm: shared attachment site at the summit of the glyph
    const topLm = cluster.landmarks[cluster.landmarks.length - 1];
    const stemY = topLm.y - HANDPRINT_LOBE_HALF_HEIGHT - 3.5;
    // Connector line from summit up to duration cue
    parts.push(
      `    <line class="janko-handprint-dur-connector" x1="${f(topLm.x)}" y1="${f(topLm.y - HANDPRINT_LOBE_HALF_HEIGHT)}" x2="${f(topLm.x)}" y2="${f(stemY + 2.0)}" stroke="#111111" stroke-width="0.75"/>`
    );
    parts.push(`    ${renderHandprintDurationCue(topLm.x, stemY, cluster.uniformDurationTicks)}`);
  } else {
    // Differing releases: visibly attached to relevant landmark shoulders
    for (const subset of cluster.durationSubsets) {
      const lm = subset.landmark;
      const isOdd = lm.parity === 1;
      const sign = isOdd ? 1 : -1;
      const attachX = lm.x + sign * (HANDPRINT_LOBE_WIDTH + 1.2);
      const cueX = attachX + sign * 2.2;
      const cueY = lm.y;

      // Small horizontal attachment line from landmark shoulder to cue
      parts.push(
        `    <line class="janko-handprint-dur-connector" x1="${f(lm.x + sign * HANDPRINT_LOBE_WIDTH)}" y1="${f(cueY)}" x2="${f(attachX)}" y2="${f(cueY)}" stroke="#111111" stroke-width="0.75"/>`
      );
      parts.push(`    ${renderHandprintDurationCue(cueX, cueY, subset.durationTicks, 0.9)}`);
    }
  }

  parts.push('  </g>');
  return {
    svg: parts.join('\n'),
    inkBox: cluster.inkBox,
  };
}

// ---------------------------------------------------------------------------
// Exact Semantics: Inverse Decoding
// ---------------------------------------------------------------------------

/**
 * Decode linear pitches from anchor pitch, displayed staff height, onset X,
 * and landmark coordinates.
 *
 * Demonstrates inverse pitch recovery strictly from geometric landmarks,
 * NOT by returning a hidden saved source-note array.
 */
export function decodeHandprintLandmarks(
  baseLin: number,
  anchorStaffY: number,
  onsetX: number,
  landmarks: readonly { x: number; y: number }[],
  u: number = HANDPRINT_PITCH_UNIT_U,
  a: number = HANDPRINT_ROW_DISPLACEMENT_A
): number[] {
  void a;
  return landmarks.map((lm) => {
    const deltaY = lm.y - anchorStaffY;
    const semitonesFromBase = Math.round(-deltaY / u);
    const recoveredPitch = baseLin + semitonesFromBase;

    // Verify parity agreement from horizontal position
    const deltaX = lm.x - onsetX;
    const expectedParity = deltaX > 0 ? 1 : 0;
    const actualParity = (recoveredPitch % 2 !== 0) ? 1 : 0;
    if (expectedParity !== actualParity) {
      throw new Error(
        `Parity mismatch during decoding: landmark at x=${lm.x.toFixed(2)} (deltaX=${deltaX.toFixed(2)}) ` +
        `implies parity ${expectedParity}, but recovered pitch ${recoveredPitch} has parity ${actualParity}`
      );
    }

    return recoveredPitch;
  });
}

/**
 * Return discrete bounding boxes for all ink primitives that make up a handprint cluster:
 * - Origin knockout and base numeral box
 * - Sounding landmark lobes
 * - Connecting calligraphic body segments
 * - Duration attachment cues and connectors
 */
export function getHandprintPrimitives(
  cluster: JankoHandprintCluster
): Array<[number, number, number, number]> {
  const boxes: Array<[number, number, number, number]> = [];
  const lms = cluster.landmarks;
  if (lms.length === 0) return boxes;

  // 1. Origin knockout / digit box
  const origin = lms[0];
  boxes.push([
    origin.x - HANDPRINT_ORIGIN_KNOCKOUT_WX,
    origin.y - HANDPRINT_ORIGIN_KNOCKOUT_HY,
    origin.x + HANDPRINT_ORIGIN_KNOCKOUT_WX,
    origin.y + HANDPRINT_ORIGIN_KNOCKOUT_HY,
  ]);

  // 2. Landmark lobes
  for (const lm of lms) {
    if (lm.parity === 1) {
      boxes.push([
        lm.x - HANDPRINT_BODY_HALF_WIDTH,
        lm.y - HANDPRINT_LOBE_HALF_HEIGHT,
        lm.x + HANDPRINT_LOBE_WIDTH,
        lm.y + HANDPRINT_LOBE_HALF_HEIGHT,
      ]);
    } else {
      boxes.push([
        lm.x - HANDPRINT_LOBE_WIDTH,
        lm.y - HANDPRINT_LOBE_HALF_HEIGHT,
        lm.x + HANDPRINT_BODY_HALF_WIDTH,
        lm.y + HANDPRINT_LOBE_HALF_HEIGHT,
      ]);
    }
  }

  // 3. Connecting segments
  for (let i = 0; i < lms.length - 1; i++) {
    const yTop = lms[i + 1].y;
    const yBot = lms[i].y;
    const minX = Math.min(lms[i].x, lms[i + 1].x) - HANDPRINT_BODY_HALF_WIDTH;
    const maxX = Math.max(lms[i].x, lms[i + 1].x) + HANDPRINT_BODY_HALF_WIDTH;
    boxes.push([minX, yTop, maxX, yBot]);
  }

  // 4. Duration attachments
  if (cluster.isUniformRhythm && cluster.uniformDurationTicks !== undefined) {
    const topLm = lms[lms.length - 1];
    const stemY = topLm.y - HANDPRINT_LOBE_HALF_HEIGHT - 3.5;
    boxes.push([topLm.x - 3.5, stemY - 4.5, topLm.x + 3.5, topLm.y]);
  } else {
    for (const subset of cluster.durationSubsets) {
      const lm = subset.landmark;
      if (lm.parity === 1) {
        boxes.push([
          lm.x + HANDPRINT_LOBE_WIDTH,
          lm.y - 3.5,
          lm.x + HANDPRINT_LOBE_WIDTH + 8.5,
          lm.y + 3.5,
        ]);
      } else {
        boxes.push([
          lm.x - HANDPRINT_LOBE_WIDTH - 8.5,
          lm.y - 3.5,
          lm.x - HANDPRINT_LOBE_WIDTH,
          lm.y + 3.5,
        ]);
      }
    }
  }

  return boxes;
}

function boxIntersectsBox(
  b1: readonly [number, number, number, number],
  b2: readonly [number, number, number, number],
  clearance: number
): boolean {
  return (
    b1[0] - clearance <= b2[2] &&
    b1[2] + clearance >= b2[0] &&
    b1[1] - clearance <= b2[3] &&
    b1[3] + clearance >= b2[1]
  );
}

// ---------------------------------------------------------------------------
// Clearance Verification
// ---------------------------------------------------------------------------

/**
 * Check whether handprint cluster ink collides with barlines, noteheads, or rests.
 * Uses a broad-phase bounding-box test followed by a narrow-phase check against
 * actual ink primitives (origin knockout, landmark lobes, connecting segments,
 * and duration attachment cues).
 */
export function checkHandprintCollisions(
  cluster: JankoHandprintCluster,
  barlineXs: readonly number[],
  independentNotes: readonly PositionedJankoNote[],
  rests: readonly any[],
  minClearance: number = 1.0
): { collides: boolean; obstacle?: string; details?: string } {
  const [minX, minY, maxX, maxY] = cluster.inkBox;
  const primitives = getHandprintPrimitives(cluster);

  // 1. Check barlines
  for (const bx of barlineXs) {
    if (bx >= minX - minClearance && bx <= maxX + minClearance) {
      for (const prim of primitives) {
        if (bx >= prim[0] - minClearance && bx <= prim[2] + minClearance) {
          return {
            collides: true,
            obstacle: 'barline',
            details: `Cluster ink touches barline at x=${bx.toFixed(1)}`,
          };
        }
      }
    }
  }

  // 2. Check independent noteheads (other hand or different onset)
  for (const n of independentNotes) {
    const noteId = n.note?.id ?? (n as any).id;
    if (cluster.allNoteIds.has(noteId)) continue;
    const nx = n.x;
    const ny = n.y;
    if (nx === undefined || ny === undefined) continue;
    const wx = 2.53;
    const hy = 3.46;
    const noteBox: [number, number, number, number] = [nx - wx, ny - hy, nx + wx, ny + hy];

    // Broad phase
    if (!boxIntersectsBox(cluster.inkBox, noteBox, minClearance)) continue;

    // Narrow phase
    for (const prim of primitives) {
      if (boxIntersectsBox(prim, noteBox, minClearance)) {
        return {
          collides: true,
          obstacle: 'notehead',
          details: `Cluster ink touches notehead ${noteId} at (${nx.toFixed(1)}, ${ny.toFixed(1)})`,
        };
      }
    }
  }

  // 3. Check rests
  for (const r of rests) {
    if (r && typeof r.x === 'number' && typeof r.y === 'number') {
      const rx = r.x;
      const ry = r.y;
      const rw = 4.0;
      const rh = 6.0;
      const restBox: [number, number, number, number] = [rx - rw, ry - rh, rx + rw, ry + rh];

      // Broad phase
      if (!boxIntersectsBox(cluster.inkBox, restBox, minClearance)) continue;

      // Narrow phase
      for (const prim of primitives) {
        if (boxIntersectsBox(prim, restBox, minClearance)) {
          return {
            collides: true,
            obstacle: 'rest',
            details: `Cluster ink touches rest at (${rx.toFixed(1)}, ${ry.toFixed(1)})`,
          };
        }
      }
    }
  }

  return { collides: false };
}
