/**
 * Mirrored Handprint — Whole-Form Cluster Element Module (Round 36 Candidate)
 * ===========================================================================
 *
 * A rotated keyboard footprint supplies glyph-local geometry for dense hand
 * clusters (4- and 5-note groups at the same onset and hand); surrounding
 * fixed-3 staff is unchanged.
 *
 * Geometry:
 * - Anchor is the lowest sounding pitch p0, with explicit absolute solf numeral
 *   and register placement coinciding with the anchor's displayed staff height.
 * - Local y[i] = -u * (p[i] - p0), increasing pitch upward (u = 2.4 pt/semitone).
 * - Local x[i] = +a for odd p[i], -a for even p[i] (a = 3.0 pt).
 * - Central axis is the onset axis.
 * - Odd-semitone transposition reflects internal form left/right;
 *   even-semitone transposition preserves it, generated by ONE mirrored geometry routine.
 * - Landmarks connected in ascending order as a single narrow, smoothly joined
 *   calligraphic body with small outward shoulders/lobes at sounding landmarks.
 * - Base numeral integrated at the origin; other numerals absent.
 * - Clearly owned duration attachments: uniform rhythm shared at summit;
 *   differing releases visibly attached to relevant landmark shoulders.
 * - Exact inverse pitch decoding recoverable from anchor + landmark geometry.
 */

import { Hand, QuantizedNote } from '../../../model/types';
import { getDuodecimalDigit } from '../../types';
import {
  JankoClusterPresentation,
  ResolvedJankoLayoutOptions,
  ResolvedJankoTokens,
} from '../types';
import { f } from './style';
import { digitBaselineOffset } from './notehead';
import type { PositionedJankoNote } from '../engine';

// ---------------------------------------------------------------------------
// Published Testable Geometry Constants
// ---------------------------------------------------------------------------

/** Pitch interval scale along glyph: 2.4 pt per semitone (28.8 pt per octave). */
export const HANDPRINT_PITCH_UNIT_U = 2.4;
export const HANDPRINT_U = HANDPRINT_PITCH_UNIT_U;

/** Horizontal displacement from central onset axis: 3.0 pt (total row span 6.0 pt). */
export const HANDPRINT_ROW_DISPLACEMENT_A = 3.0;
export const HANDPRINT_A = HANDPRINT_ROW_DISPLACEMENT_A;

/** Outward shoulder/lobe horizontal reach from landmark center (pt) for Round 36. */
export const HANDPRINT_LOBE_WIDTH = 2.0;

/** Outward shoulder/lobe vertical half-height (pt) for Round 36. */
export const HANDPRINT_LOBE_HALF_HEIGHT = 1.1;

/** Narrow connecting calligraphic body half-width (pt) for Round 36. */
export const HANDPRINT_BODY_HALF_WIDTH = 0.8;

/** Origin base numeral knockout half-width (pt). */
export const HANDPRINT_ORIGIN_KNOCKOUT_WX = 2.4;

/** Origin base numeral knockout half-height (pt). */
export const HANDPRINT_ORIGIN_KNOCKOUT_HY = 3.2;

// --- Round 37 Constants (Intrinsically indexed symmetric cluster) ---

/** Slender stroked body path stroke width for Round 37 indexed symmetric cluster (0.5 pt). */
export const INDEXED_SYMMETRIC_BODY_STROKE = 0.5;

/** Intrinsic scale reference division width (pt): centered inside the form (2.4 pt). */
export const INDEXED_SYMMETRIC_DIVISION_WIDTH = 2.4;

/** Intrinsic scale reference division stroke width (0.35 pt, lighter than body). */
export const INDEXED_SYMMETRIC_DIVISION_STROKE = 0.35;

/** Intrinsic scale octave (10-span boundary, multiple of 12) division width (4.0 pt). */
export const INDEXED_SYMMETRIC_OCTAVE_DIVISION_WIDTH = 4.0;

/** Intrinsic scale octave division stroke width (0.5 pt). */
export const INDEXED_SYMMETRIC_OCTAVE_DIVISION_STROKE = 0.5;

/** Paired outward articulation horizontal reach from landmark track (pt). */
export const INDEXED_SYMMETRIC_LANDMARK_REACH = 1.8;

/** Paired outward articulation stroke width (0.6 pt). */
export const INDEXED_SYMMETRIC_LANDMARK_STROKE = 0.6;

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

/** Sounding landmark of one constituent pitch in a handprint cluster. */
export interface JankoHandprintLandmark {
  /** Sounding linear pitch: 12 * octave + pitchClass. */
  pitch: number;
  /** Pitch class (0..11). */
  pitchClass: number;
  /** Parity: 0 for even, 1 for odd. */
  parity: 0 | 1;
  /** Local horizontal offset from onset axis (pt): +a for odd, -a for even. */
  localX: number;
  /** Local vertical offset from anchor staff height (pt): -u * (pitch - p0). */
  localY: number;
  /** Page absolute X (pt): onsetX + localX. */
  x: number;
  /** Page absolute Y (pt): anchorStaffY + localY. */
  y: number;
  /** Duration (ticks) of this constituent note. */
  durationTicks: number;
  /** Source note ID. */
  noteId: string;
}

/** Distinct duration release subset within a handprint cluster. */
export interface JankoHandprintDurationSubset {
  durationTicks: number;
  noteIds: string[];
  /** Landmark this duration attachment owns and attaches to. */
  landmark: JankoHandprintLandmark;
}

/** Intrinsic scale reference division in an indexed symmetric cluster form. */
export interface JankoHandprintScaleDivision {
  /** Offset in semitones from anchor (0, 2, 4, ...). */
  offset: number;
  /** Page absolute Y coordinate (pt). */
  y: number;
  /** True if offset > 0 and offset is a multiple of 12 semitones (duodecimal 10-span). */
  isOctave: boolean;
  /** Transverse line width in pt. */
  width: number;
  /** Stroke width in pt. */
  strokeWidth: number;
}

/** Contiguous run of landmarks sharing the exact same duration. */
export interface JankoHandprintDurationRun {
  durationTicks: number;
  noteIds: string[];
  landmarks: JankoHandprintLandmark[];
}

/** One candidate handprint cluster representing a dense 4/5-note chord. */
export interface JankoHandprintCluster {
  id: string;
  startTick: number;
  hand: Hand;
  /** Sounding linear pitch of the anchor (lowest note). */
  baseLin: number;
  /** Anchor pitch class (0..11). */
  basePitchClass: number;
  /** Displayed staff height of the anchor note (page pt). */
  anchorStaffY: number;
  /** Central onset axis column on page (pt). */
  onsetX: number;
  /** Sounding landmarks in ascending pitch order. */
  landmarks: JankoHandprintLandmark[];
  /** Set of all source note IDs in this cluster. */
  allNoteIds: Set<string>;
  /** Positioned notes belonging to this cluster. */
  notes: PositionedJankoNote[];
  /** Bounding box of all ink: [minX, minY, maxX, maxY] in page pt. */
  inkBox: [number, number, number, number];
  /** Distinct duration release subsets. */
  durationSubsets: JankoHandprintDurationSubset[];
  /** True if all constituent notes share the exact same duration. */
  isUniformRhythm: boolean;
  /** The uniform duration in ticks (if uniform). */
  uniformDurationTicks?: number;
  /** Active cluster presentation candidate. */
  presentation?: JankoClusterPresentation;
  /** True when anchor is shared with LH unison bass note (m.60). */
  hasSharedAnchor?: boolean;
  /** Note ID of the surviving shared bass anchor note (e.g. LH survivor in m.60). */
  sharedBassSurvivorId?: string;
  /** Transverse reference divisions (Round 37). */
  scaleDivisions?: JankoHandprintScaleDivision[];
  /** Contiguous duration runs for explicit visible ownership (Round 37). */
  durationRuns?: JankoHandprintDurationRun[];
}

// ---------------------------------------------------------------------------
// Forward Geometry & Clustering
// ---------------------------------------------------------------------------

/** Get sounding linear pitch from a note or positioned note. */
export function getSoundingPitch(note: QuantizedNote | PositionedJankoNote): number {
  const q = 'note' in note ? note.note : note;
  const pc = ((q.pitch.pitchClass % 12) + 12) % 12;
  return q.pitch.octave * 12 + pc;
}

/**
 * Group positioned notes into handprint clusters.
 * Focus: same-hand, same-onset 4- and 5-note groups (>= 4 notes).
 * 2/3-note groups stay literal for this experiment.
 */
export function groupHandprintClusters(
  notes: readonly PositionedJankoNote[],
  u: number = HANDPRINT_PITCH_UNIT_U,
  a: number = HANDPRINT_ROW_DISPLACEMENT_A,
  presentation: JankoClusterPresentation = 'mirrored-handprint'
): {
  clusters: JankoHandprintCluster[];
  handprintNoteIds: Set<string>;
} {
  const isIndexedSymmetric = presentation === 'indexed-symmetric';

  // Group notes by startTick and hand
  const byOnset = new Map<string, PositionedJankoNote[]>();
  for (const n of notes) {
    const k = `${n.note.startTick}_${n.note.hand}`;
    const list = byOnset.get(k);
    if (list) {
      list.push(n);
    } else {
      byOnset.set(k, [n]);
    }
  }

  const clusters: JankoHandprintCluster[] = [];
  const handprintNoteIds = new Set<string>();

  for (const group of byOnset.values()) {
    if (group.length < 4) continue; // 2/3-note groups stay literal

    // Sort constituent notes strictly ascending by sounding linear pitch
    const sorted = [...group].sort((n1, n2) => getSoundingPitch(n1) - getSoundingPitch(n2));
    const anchorNote = sorted[0];
    const baseLin = getSoundingPitch(anchorNote);
    const basePitchClass = ((baseLin % 12) + 12) % 12;
    const anchorStaffY = anchorNote.y;

    // The onset axis is the nominal unshifted column X of the onset
    // In Janko layout, anchorNote.x sits on the onset column
    const onsetX = Math.min(...group.map((n) => n.x));

    const landmarks: JankoHandprintLandmark[] = sorted.map((n) => {
      const pitch = getSoundingPitch(n);
      const pc = ((pitch % 12) + 12) % 12;
      const parity: 0 | 1 = (pitch % 2 !== 0) ? 1 : 0;
      const localX = parity === 1 ? +a : -a;
      const localY = -u * (pitch - baseLin);
      return {
        pitch,
        pitchClass: pc,
        parity,
        localX,
        localY,
        x: onsetX + localX,
        y: anchorStaffY + localY,
        durationTicks: n.note.durationTicks,
        noteId: n.note.id,
      };
    });

    // Partition by duration ticks
    const durMap = new Map<number, JankoHandprintLandmark[]>();
    for (const lm of landmarks) {
      const list = durMap.get(lm.durationTicks);
      if (list) list.push(lm);
      else durMap.set(lm.durationTicks, [lm]);
    }

    const isUniformRhythm = durMap.size === 1;
    const uniformDurationTicks = isUniformRhythm ? landmarks[0].durationTicks : undefined;

    const durationSubsets: JankoHandprintDurationSubset[] = [];
    for (const [dur, lms] of durMap.entries()) {
      // Owned attachment site: the highest landmark in this duration subset
      const highestLm = lms[lms.length - 1];
      durationSubsets.push({
        durationTicks: dur,
        noteIds: lms.map((l) => l.noteId),
        landmark: highestLm,
      });
    }

    // Sort duration subsets ascending by duration
    durationSubsets.sort((x1, x2) => x1.durationTicks - x2.durationTicks);

    let minX: number;
    let maxX: number;
    let minY: number;
    let maxY: number;
    let hasSharedAnchor: boolean | undefined;
    let sharedBassSurvivorId: string | undefined;
    let scaleDivisions: JankoHandprintScaleDivision[] | undefined;
    let durationRuns: JankoHandprintDurationRun[] | undefined;

    if (isIndexedSymmetric) {
      // Round 37: check for shared bass anchor (cross-hand unison merged survivor)
      hasSharedAnchor = !!anchorNote.unisonSurvivorId;
      sharedBassSurvivorId = anchorNote.unisonSurvivorId;

      // Scale divisions at offsets 0, 2, 4, ... semitones from anchor
      const maxOffset = getSoundingPitch(sorted[sorted.length - 1]) - baseLin;
      const maxDivOffset = (maxOffset % 2 === 0) ? maxOffset : maxOffset + 1;
      scaleDivisions = [];
      for (let d = 0; d <= maxDivOffset; d += 2) {
        const isOctave = d > 0 && d % 12 === 0;
        scaleDivisions.push({
          offset: d,
          y: anchorStaffY - u * d,
          isOctave,
          width: isOctave ? INDEXED_SYMMETRIC_OCTAVE_DIVISION_WIDTH : INDEXED_SYMMETRIC_DIVISION_WIDTH,
          strokeWidth: isOctave ? INDEXED_SYMMETRIC_OCTAVE_DIVISION_STROKE : INDEXED_SYMMETRIC_DIVISION_STROKE,
        });
      }

      // Contiguous duration runs for explicit visible ownership
      durationRuns = [];
      let currentRun: JankoHandprintLandmark[] = [landmarks[0]];
      for (let i = 1; i < landmarks.length; i++) {
        if (landmarks[i].durationTicks === currentRun[0].durationTicks) {
          currentRun.push(landmarks[i]);
        } else {
          durationRuns.push({
            durationTicks: currentRun[0].durationTicks,
            noteIds: currentRun.map((l) => l.noteId),
            landmarks: currentRun,
          });
          currentRun = [landmarks[i]];
        }
      }
      durationRuns.push({
        durationTicks: currentRun[0].durationTicks,
        noteIds: currentRun.map((l) => l.noteId),
        landmarks: currentRun,
      });

      // Compute ink bounding box
      minX = onsetX - a - INDEXED_SYMMETRIC_LANDMARK_REACH;
      maxX = onsetX + a + INDEXED_SYMMETRIC_LANDMARK_REACH;
      const topDivY = anchorStaffY - u * maxDivOffset;
      minY = Math.min(topDivY, landmarks[landmarks.length - 1].y);
      maxY = anchorStaffY;

      if (!hasSharedAnchor) {
        minX = Math.min(minX, onsetX - HANDPRINT_ORIGIN_KNOCKOUT_WX);
        maxX = Math.max(maxX, onsetX + HANDPRINT_ORIGIN_KNOCKOUT_WX);
        minY = Math.min(minY, anchorStaffY - HANDPRINT_ORIGIN_KNOCKOUT_HY);
        maxY = Math.max(maxY, anchorStaffY + HANDPRINT_ORIGIN_KNOCKOUT_HY);
      }

      // Account for duration attachments on right side
      maxX = Math.max(maxX, onsetX + a + INDEXED_SYMMETRIC_LANDMARK_REACH + 1.2 + 3.0 + 3.5);
      minY = Math.min(minY, ...landmarks.map((l) => l.y - 3.5));
      maxY = Math.max(maxY, ...landmarks.map((l) => l.y + 3.5));
    } else {
      // Round 36: mirrored handprint bounding box
      minX = onsetX - a - HANDPRINT_LOBE_WIDTH;
      maxX = onsetX + a + HANDPRINT_LOBE_WIDTH;
      minY = landmarks[landmarks.length - 1].y - HANDPRINT_LOBE_HALF_HEIGHT;
      maxY = anchorStaffY + HANDPRINT_LOBE_HALF_HEIGHT;

      // Account for origin knockout/digit
      minX = Math.min(minX, onsetX - a - HANDPRINT_ORIGIN_KNOCKOUT_WX);
      maxX = Math.max(maxX, onsetX + a + HANDPRINT_ORIGIN_KNOCKOUT_WX);
      minY = Math.min(minY, anchorStaffY - HANDPRINT_ORIGIN_KNOCKOUT_HY);
      maxY = Math.max(maxY, anchorStaffY + HANDPRINT_ORIGIN_KNOCKOUT_HY);

      if (isUniformRhythm) {
        minY -= 9.0; // Summit duration cue extends upward
      } else {
        maxX += 8.0; // Differing release cues extend outward
        minX -= 4.0;
      }
    }

    const cluster: JankoHandprintCluster = {
      id: `handprint-${anchorNote.note.startTick}-${anchorNote.note.hand}`,
      startTick: anchorNote.note.startTick,
      hand: anchorNote.note.hand,
      baseLin,
      basePitchClass,
      anchorStaffY,
      onsetX,
      landmarks,
      allNoteIds: new Set(group.map((n) => n.note.id)),
      notes: sorted,
      inkBox: [minX, minY, maxX, maxY],
      durationSubsets,
      isUniformRhythm,
      uniformDurationTicks,
      presentation,
      hasSharedAnchor,
      sharedBassSurvivorId,
      scaleDivisions,
      durationRuns,
    };

    clusters.push(cluster);
    for (const n of group) {
      handprintNoteIds.add(n.note.id);
    }
  }

  return { clusters, handprintNoteIds };
}

// ---------------------------------------------------------------------------
// Calligraphic Body Path Generation
// ---------------------------------------------------------------------------

/**
 * Construct the SVG path data for the single narrow, smoothly joined calligraphic body.
 * Connects landmarks in ascending order with small outward shoulders/lobes at sounding landmarks.
 *
 * This routine is purely mirrored: odd transposition reflects x left/right;
 * even transposition preserves geometry identically.
 */
export function renderHandprintBodyPath(
  landmarks: readonly JankoHandprintLandmark[],
  wLobe: number = HANDPRINT_LOBE_WIDTH,
  hLobe: number = HANDPRINT_LOBE_HALF_HEIGHT,
  wBody: number = HANDPRINT_BODY_HALF_WIDTH
): string {
  if (landmarks.length === 0) return '';
  const n = landmarks.length;

  // Build right-side contour ascending from landmark 0 to n-1
  const rightPoints: Array<{ x: number; y: number; cmd?: string; cp1?: { x: number; y: number }; cp2?: { x: number; y: number } }> = [];

  for (let i = 0; i < n; i++) {
    const lm = landmarks[i];
    const isOdd = lm.parity === 1;

    if (isOdd) {
      // Landmark is on right (+a). Outward shoulder/lobe swells outward to the right (+x)
      const xBase = lm.x + wBody;
      const xApex = lm.x + wLobe;
      const yBot = lm.y + hLobe;
      const yMid = lm.y;
      const yTop = lm.y - hLobe;

      // Start of lobe, curve to apex, curve back to body
      rightPoints.push({ x: xBase, y: yBot, cmd: 'L' });
      rightPoints.push({
        x: xApex,
        y: yMid,
        cmd: 'C',
        cp1: { x: xApex, y: yBot },
        cp2: { x: xApex, y: yMid + 0.3 * hLobe },
      });
      rightPoints.push({
        x: xBase,
        y: yTop,
        cmd: 'C',
        cp1: { x: xApex, y: yMid - 0.3 * hLobe },
        cp2: { x: xApex, y: yTop },
      });
    } else {
      // Landmark is on left (-a). Right side is the inward body boundary
      const xInward = lm.x + wBody;
      rightPoints.push({ x: xInward, y: lm.y, cmd: 'L' });
    }
  }

  // Summit transition: wrap over the top landmark (n - 1)
  const topLm = landmarks[n - 1];
  const summitOver = {
    x: topLm.x,
    y: topLm.y - hLobe - 0.5,
  };

  // Build left-side contour descending from landmark n-1 down to 0
  const leftPoints: Array<{ x: number; y: number; cmd?: string; cp1?: { x: number; y: number }; cp2?: { x: number; y: number } }> = [];

  for (let i = n - 1; i >= 0; i--) {
    const lm = landmarks[i];
    const isEven = lm.parity === 0;

    if (isEven) {
      // Landmark is on left (-a). Outward shoulder/lobe swells outward to the left (-x)
      const xBase = lm.x - wBody;
      const xApex = lm.x - wLobe;
      const yTop = lm.y - hLobe;
      const yMid = lm.y;
      const yBot = lm.y + hLobe;

      leftPoints.push({ x: xBase, y: yTop, cmd: 'L' });
      leftPoints.push({
        x: xApex,
        y: yMid,
        cmd: 'C',
        cp1: { x: xApex, y: yTop },
        cp2: { x: xApex, y: yMid - 0.3 * hLobe },
      });
      leftPoints.push({
        x: xBase,
        y: yBot,
        cmd: 'C',
        cp1: { x: xApex, y: yMid + 0.3 * hLobe },
        cp2: { x: xApex, y: yBot },
      });
    } else {
      // Landmark is on right (+a). Left side is the inward body boundary
      const xInward = lm.x - wBody;
      leftPoints.push({ x: xInward, y: lm.y, cmd: 'L' });
    }
  }

  // Base transition: wrap under the bottom landmark (0)
  const botLm = landmarks[0];
  const baseUnder = {
    x: botLm.x,
    y: botLm.y + hLobe + 0.5,
  };

  // Assemble the closed SVG path string
  const dParts: string[] = [];
  const start = rightPoints[0];
  dParts.push(`M ${f(start.x)} ${f(start.y)}`);

  for (let i = 1; i < rightPoints.length; i++) {
    const pt = rightPoints[i];
    if (pt.cmd === 'C' && pt.cp1 && pt.cp2) {
      dParts.push(`C ${f(pt.cp1.x)} ${f(pt.cp1.y)}, ${f(pt.cp2.x)} ${f(pt.cp2.y)}, ${f(pt.x)} ${f(pt.y)}`);
    } else {
      dParts.push(`L ${f(pt.x)} ${f(pt.y)}`);
    }
  }

  // Over summit
  dParts.push(`Q ${f(summitOver.x)} ${f(summitOver.y)}, ${f(leftPoints[0].x)} ${f(leftPoints[0].y)}`);

  for (let i = 1; i < leftPoints.length; i++) {
    const pt = leftPoints[i];
    if (pt.cmd === 'C' && pt.cp1 && pt.cp2) {
      dParts.push(`C ${f(pt.cp1.x)} ${f(pt.cp1.y)}, ${f(pt.cp2.x)} ${f(pt.cp2.y)}, ${f(pt.x)} ${f(pt.y)}`);
    } else {
      dParts.push(`L ${f(pt.x)} ${f(pt.y)}`);
    }
  }

  // Under base and close
  dParts.push(`Q ${f(baseUnder.x)} ${f(baseUnder.y)}, ${f(start.x)} ${f(start.y)}`);
  dParts.push('Z');

  return dParts.join(' ');
}

// ---------------------------------------------------------------------------
// Duration Attachment Symbols (Existing Vocabulary)
// ---------------------------------------------------------------------------

/**
 * Render standard duration cue mark:
 * - 192 ticks (whole): double open ring
 * - 144 ticks (dotted half): open ring + augmentation dot
 * - 96 ticks (half): single open ring
 * - 48 ticks (quarter): plain vertical stem tick
 * - 24 ticks (eighth): stem tick + flag notch
 */
export function renderHandprintDurationCue(
  x: number,
  y: number,
  durationTicks: number,
  scale: number = 1.0
): string {
  const r = 1.35 * scale;
  const dotR = 0.9 * scale;
  const strokeWidth = 0.65 * scale;
  const parts: string[] = [];

  if (durationTicks >= 192) {
    // Double open ring (whole note)
    parts.push(
      `<circle class="janko-handprint-dur-ring" cx="${f(x)}" cy="${f(y - r - 0.4)}" r="${f(r)}" fill="#FFFFFF" stroke="#111111" stroke-width="${f(strokeWidth)}"/>`
    );
    parts.push(
      `<circle class="janko-handprint-dur-ring" cx="${f(x)}" cy="${f(y + r + 0.4)}" r="${f(r)}" fill="#FFFFFF" stroke="#111111" stroke-width="${f(strokeWidth)}"/>`
    );
  } else if (durationTicks === 144) {
    // Single open ring + augmentation dot (dotted half)
    parts.push(
      `<circle class="janko-handprint-dur-ring" cx="${f(x)}" cy="${f(y)}" r="${f(r)}" fill="#FFFFFF" stroke="#111111" stroke-width="${f(strokeWidth)}"/>`
    );
    parts.push(
      `<circle class="janko-handprint-dur-dot" cx="${f(x + r + dotR + 1.2)}" cy="${f(y)}" r="${f(dotR)}" fill="#111111"/>`
    );
  } else if (durationTicks >= 96) {
    // Single open ring (half note)
    parts.push(
      `<circle class="janko-handprint-dur-ring" cx="${f(x)}" cy="${f(y)}" r="${f(r)}" fill="#FFFFFF" stroke="#111111" stroke-width="${f(strokeWidth)}"/>`
    );
  } else if (durationTicks >= 48) {
    // Plain quarter stem tick
    parts.push(
      `<line class="janko-handprint-dur-stem" x1="${f(x)}" y1="${f(y - 3.5 * scale)}" x2="${f(x)}" y2="${f(y + 3.5 * scale)}" stroke="#111111" stroke-width="${f(0.85 * scale)}"/>`
    );
  } else if (durationTicks >= 24) {
    // Eighth note stem tick + flag
    parts.push(
      `<line class="janko-handprint-dur-stem" x1="${f(x)}" y1="${f(y - 3.5 * scale)}" x2="${f(x)}" y2="${f(y + 3.5 * scale)}" stroke="#111111" stroke-width="${f(0.85 * scale)}"/>`
    );
    parts.push(
      `<line class="janko-handprint-dur-flag" x1="${f(x)}" y1="${f(y - 2.5 * scale)}" x2="${f(x + 2.5 * scale)}" y2="${f(y - 0.8 * scale)}" stroke="#111111" stroke-width="${f(0.75 * scale)}"/>`
    );
  } else {
    // 16th note stem tick + double flag
    parts.push(
      `<line class="janko-handprint-dur-stem" x1="${f(x)}" y1="${f(y - 3.5 * scale)}" x2="${f(x)}" y2="${f(y + 3.5 * scale)}" stroke="#111111" stroke-width="${f(0.85 * scale)}"/>`
    );
    parts.push(
      `<line class="janko-handprint-dur-flag" x1="${f(x)}" y1="${f(y - 2.8 * scale)}" x2="${f(x + 2.5 * scale)}" y2="${f(y - 1.2 * scale)}" stroke="#111111" stroke-width="${f(0.75 * scale)}"/>`
    );
    parts.push(
      `<line class="janko-handprint-dur-flag" x1="${f(x)}" y1="${f(y - 1.2 * scale)}" x2="${f(x + 2.5 * scale)}" y2="${f(y + 0.4 * scale)}" stroke="#111111" stroke-width="${f(0.75 * scale)}"/>`
    );
  }

  return parts.join('');
}

// ---------------------------------------------------------------------------
// SVG Assembly
// ---------------------------------------------------------------------------

/**
 * Render the slender stroked body paths for an indexed symmetric cluster (Round 37):
 * - Primary path connects ascending landmarks on parity tracks:
 *   +a for odd pitch, -a for even pitch.
 * - Reflected counterpart reflects the path about the central onset axis.
 * - Reflected counterparts denote ONE note, not a second occurrence.
 * - Central crossings are unadorned and never sound.
 */
export function renderIndexedSymmetricBodyPaths(
  landmarks: readonly JankoHandprintLandmark[],
  strokeWidth: number = INDEXED_SYMMETRIC_BODY_STROKE
): string {
  if (landmarks.length === 0) return '';
  const primaryPoints: string[] = [];
  const reflectedPoints: string[] = [];
  const onsetX = landmarks[0].x - landmarks[0].localX;

  for (let i = 0; i < landmarks.length; i++) {
    const lm = landmarks[i];
    const px = lm.x;
    const py = lm.y;
    const rx = 2 * onsetX - px;
    const ry = py;
    if (i === 0) {
      primaryPoints.push(`M ${f(px)} ${f(py)}`);
      reflectedPoints.push(`M ${f(rx)} ${f(ry)}`);
    } else {
      primaryPoints.push(`L ${f(px)} ${f(py)}`);
      reflectedPoints.push(`L ${f(rx)} ${f(ry)}`);
    }
  }

  return [
    `    <path class="janko-symmetric-body" d="${primaryPoints.join(' ')}" fill="none" stroke="#111111" stroke-width="${f(strokeWidth)}"/>`,
    `    <path class="janko-symmetric-body" d="${reflectedPoints.join(' ')}" fill="none" stroke="#111111" stroke-width="${f(strokeWidth)}"/>`,
  ].join('\n');
}

/**
 * Render short, light transverse scale divisions centered inside the form (Round 37).
 * Placed at offsets 0, 2, 4, ... semitones from anchor; octave divisions (multiples of 12)
 * are distinguished (10-span boundary). Offset 0 yields to the anchor's protected numeral.
 */
export function renderIndexedSymmetricDivisions(
  divisions: readonly JankoHandprintScaleDivision[],
  onsetX: number
): string {
  const parts: string[] = [];
  for (const div of divisions) {
    if (div.offset === 0) continue; // Origin division yields to anchor numeral
    const halfW = div.width / 2;
    const cls = div.isOctave ? 'janko-symmetric-division-octave' : 'janko-symmetric-division';
    parts.push(
      `    <line class="${cls}" x1="${f(onsetX - halfW)}" y1="${f(div.y)}" x2="${f(onsetX + halfW)}" y2="${f(div.y)}" stroke="#111111" stroke-width="${f(div.strokeWidth)}"/>`
    );
  }
  return parts.join('\n');
}

/**
 * Render sounding landmarks as paired outward articulations (Round 37):
 * Left tick reaches outward to the left from -a; right tick reaches outward to the right from +a.
 * These stay external (|x - onsetX| >= a), distinguishing them from internal divisions and central crossings.
 */
export function renderIndexedSymmetricLandmarks(
  landmarks: readonly JankoHandprintLandmark[],
  onsetX: number,
  a: number = HANDPRINT_ROW_DISPLACEMENT_A,
  reach: number = INDEXED_SYMMETRIC_LANDMARK_REACH,
  strokeWidth: number = INDEXED_SYMMETRIC_LANDMARK_STROKE
): string {
  const parts: string[] = [];
  for (const lm of landmarks) {
    // Left outward tick
    parts.push(
      `    <line class="janko-symmetric-landmark" x1="${f(onsetX - a)}" y1="${f(lm.y)}" x2="${f(onsetX - a - reach)}" y2="${f(lm.y)}" stroke="#111111" stroke-width="${f(strokeWidth)}"/>`
    );
    // Right outward tick
    parts.push(
      `    <line class="janko-symmetric-landmark" x1="${f(onsetX + a)}" y1="${f(lm.y)}" x2="${f(onsetX + a + reach)}" y2="${f(lm.y)}" stroke="#111111" stroke-width="${f(strokeWidth)}"/>`
    );
  }
  return parts.join('\n');
}

/**
 * Render explicit visible duration ownership at sounding landmarks (Round 37):
 * Single-member subsets attach individually; multi-member runs are joined by a visible
 * connecting rail specifying every member of the run. Noncontiguous subsets remain decodable.
 */
export function renderIndexedSymmetricDurationAttachments(
  cluster: JankoHandprintCluster,
  a: number = HANDPRINT_ROW_DISPLACEMENT_A,
  reach: number = INDEXED_SYMMETRIC_LANDMARK_REACH
): string {
  const parts: string[] = [];
  const runs = cluster.durationRuns ?? [];
  const onsetX = cluster.onsetX;
  const artRightX = onsetX + a + reach;
  const xConn = artRightX + 1.2;
  const xCue = xConn + 3.0;

  for (const run of runs) {
    if (run.landmarks.length === 1) {
      // Individual landmark attachment
      const lm = run.landmarks[0];
      parts.push(
        `    <line class="janko-symmetric-dur-connector" x1="${f(artRightX)}" y1="${f(lm.y)}" x2="${f(xCue - 2.0)}" y2="${f(lm.y)}" stroke="#111111" stroke-width="0.75"/>`
      );
      parts.push(`    ${renderHandprintDurationCue(xCue, lm.y, run.durationTicks, 0.9)}`);
    } else {
      // Multi-note run: visible vertical rail connecting all members
      const firstLm = run.landmarks[0];
      const lastLm = run.landmarks[run.landmarks.length - 1];
      const yMid = (firstLm.y + lastLm.y) / 2;

      // Connect each landmark's articulation to the rail
      for (const lm of run.landmarks) {
        parts.push(
          `    <line class="janko-symmetric-dur-connector" x1="${f(artRightX)}" y1="${f(lm.y)}" x2="${f(xConn)}" y2="${f(lm.y)}" stroke="#111111" stroke-width="0.75"/>`
        );
      }
      // Vertical rail specifying every member of the run
      parts.push(
        `    <line class="janko-symmetric-dur-rail" x1="${f(xConn)}" y1="${f(lastLm.y)}" x2="${f(xConn)}" y2="${f(firstLm.y)}" stroke="#111111" stroke-width="0.75"/>`
      );
      // Connector from rail to cue
      parts.push(
        `    <line class="janko-symmetric-dur-connector" x1="${f(xConn)}" y1="${f(yMid)}" x2="${f(xCue - 2.0)}" y2="${f(yMid)}" stroke="#111111" stroke-width="0.75"/>`
      );
      // Shared duration cue
      parts.push(`    ${renderHandprintDurationCue(xCue, yMid, run.durationTicks, 0.9)}`);
    }
  }

  return parts.join('\n');
}

/**
 * Render the complete Round 37 intrinsically indexed symmetric cluster SVG group:
 * 1. Internal 2-semitone reference divisions
 * 2. Slender stroked symmetric pitch body paths (0.5pt, fill none)
 * 3. Paired outward sounding articulations (landmarks)
 * 4. Origin base numeral knockout and upright digit (or reused shared bass anchor)
 * 5. Explicit visible duration ownership at sounding landmarks
 */
export function renderIndexedSymmetricSvg(
  cluster: JankoHandprintCluster,
  tokens: ResolvedJankoTokens
): { svg: string; inkBox: [number, number, number, number] } {
  const parts: string[] = [];
  parts.push(`  <g class="janko-indexed-symmetric" data-cluster-id="${cluster.id}">`);

  // 1. Intrinsic scale reference divisions (internal)
  if (cluster.scaleDivisions && cluster.scaleDivisions.length > 0) {
    parts.push(renderIndexedSymmetricDivisions(cluster.scaleDivisions, cluster.onsetX));
  }

  // 2. Slender stroked symmetric pitch body paths (0.5pt, fill none)
  parts.push(renderIndexedSymmetricBodyPaths(cluster.landmarks));

  // 3. Sounding landmarks: paired outward articulations
  parts.push(renderIndexedSymmetricLandmarks(cluster.landmarks, cluster.onsetX));

  // 4. Anchor protected numeral (unless shared bass anchor)
  if (!cluster.hasSharedAnchor) {
    const digit = getDuodecimalDigit(cluster.basePitchClass);
    const baseline = cluster.anchorStaffY + digitBaselineOffset(tokens.digitFontSize);
    const kwx = HANDPRINT_ORIGIN_KNOCKOUT_WX;
    const khy = HANDPRINT_ORIGIN_KNOCKOUT_HY;

    parts.push(
      `    <rect class="janko-knockout" x="${f(cluster.onsetX - kwx)}" y="${f(cluster.anchorStaffY - khy)}" width="${f(2 * kwx)}" height="${f(2 * khy)}" fill="#FFFFFF"/>`
    );
    parts.push(
      `    <text class="janko-digit" x="${f(cluster.onsetX)}" y="${f(baseline)}" font-weight="700" font-size="${tokens.digitFontSize.toFixed(1)}pt" fill="#111111">${digit}</text>`
    );
  }

  // 5. Explicit visible duration ownership at sounding landmarks
  parts.push(renderIndexedSymmetricDurationAttachments(cluster));

  parts.push('  </g>');
  return {
    svg: parts.join('\n'),
    inkBox: cluster.inkBox,
  };
}

/**
 * Render the complete mirrored handprint SVG group for one cluster:
 * 1. Connected calligraphic body `<path class="janko-handprint-body" ...>`
 * 2. Origin base numeral with white knockout and duodecimal digit
 * 3. Clearly owned duration attachments
 */
export function renderHandprintSvg(
  cluster: JankoHandprintCluster,
  tokens: ResolvedJankoTokens
): { svg: string; inkBox: [number, number, number, number] } {
  if (cluster.presentation === 'indexed-symmetric') {
    return renderIndexedSymmetricSvg(cluster, tokens);
  }

  const parts: string[] = [];
  parts.push(`  <g class="janko-mirrored-handprint" data-cluster-id="${cluster.id}">`);

  // 1. Single connected calligraphic body path
  const bodyPathD = renderHandprintBodyPath(cluster.landmarks);
  parts.push(
    `    <path class="janko-handprint-body" d="${bodyPathD}" fill="#111111" stroke="none"/>`
  );

  // 2. Base numeral integrated at the origin (landmark 0)
  const originLm = cluster.landmarks[0];
  const digit = getDuodecimalDigit(cluster.basePitchClass);
  const baseline = originLm.y + digitBaselineOffset(tokens.digitFontSize);
  const kwx = HANDPRINT_ORIGIN_KNOCKOUT_WX;
  const khy = HANDPRINT_ORIGIN_KNOCKOUT_HY;

  // White knockout behind the base digit
  parts.push(
    `    <rect class="janko-knockout" x="${f(originLm.x - kwx)}" y="${f(originLm.y - khy)}" width="${f(2 * kwx)}" height="${f(2 * khy)}" fill="#FFFFFF"/>`
  );
  // Upright, readable duodecimal digit (never mirrored)
  parts.push(
    `    <text class="janko-digit" x="${f(originLm.x)}" y="${f(baseline)}" font-weight="700" font-size="${tokens.digitFontSize.toFixed(1)}pt" fill="#111111">${digit}</text>`
  );

  // 3. Clearly owned duration attachments
  if (cluster.isUniformRhythm && cluster.uniformDurationTicks !== undefined) {
    // Uniform rhythm: shared attachment site at the summit of the glyph
    const topLm = cluster.landmarks[cluster.landmarks.length - 1];
    const stemY = topLm.y - HANDPRINT_LOBE_HALF_HEIGHT - 3.5;
    // Connector line from summit up to duration cue
    parts.push(
      `    <line class="janko-handprint-dur-connector" x1="${f(topLm.x)}" y1="${f(topLm.y - HANDPRINT_LOBE_HALF_HEIGHT)}" x2="${f(topLm.x)}" y2="${f(stemY + 2.0)}" stroke="#111111" stroke-width="0.75"/>`
    );
    parts.push(`    ${renderHandprintDurationCue(topLm.x, stemY, cluster.uniformDurationTicks)}`);
  } else {
    // Differing releases: visibly attached to relevant landmark shoulders
    for (const subset of cluster.durationSubsets) {
      const lm = subset.landmark;
      const isOdd = lm.parity === 1;
      const sign = isOdd ? 1 : -1;
      const attachX = lm.x + sign * (HANDPRINT_LOBE_WIDTH + 1.2);
      const cueX = attachX + sign * 2.2;
      const cueY = lm.y;

      // Small horizontal attachment line from landmark shoulder to cue
      parts.push(
        `    <line class="janko-handprint-dur-connector" x1="${f(lm.x + sign * HANDPRINT_LOBE_WIDTH)}" y1="${f(cueY)}" x2="${f(attachX)}" y2="${f(cueY)}" stroke="#111111" stroke-width="0.75"/>`
      );
      parts.push(`    ${renderHandprintDurationCue(cueX, cueY, subset.durationTicks, 0.9)}`);
    }
  }

  parts.push('  </g>');
  return {
    svg: parts.join('\n'),
    inkBox: cluster.inkBox,
  };
}

// ---------------------------------------------------------------------------
// Exact Semantics: Inverse Decoding
// ---------------------------------------------------------------------------

/**
 * Decode linear pitches from anchor pitch, displayed staff height, onset X,
 * and landmark coordinates (Round 36).
 */
export function decodeHandprintLandmarks(
  baseLin: number,
  anchorStaffY: number,
  onsetX: number,
  landmarks: readonly { x: number; y: number }[],
  u: number = HANDPRINT_PITCH_UNIT_U,
  a: number = HANDPRINT_ROW_DISPLACEMENT_A
): number[] {
  void a;
  return landmarks.map((lm) => {
    const deltaY = lm.y - anchorStaffY;
    const semitonesFromBase = Math.round(-deltaY / u);
    const recoveredPitch = baseLin + semitonesFromBase;

    // Verify parity agreement from horizontal position
    const deltaX = lm.x - onsetX;
    const expectedParity = deltaX > 0 ? 1 : 0;
    const actualParity = (recoveredPitch % 2 !== 0) ? 1 : 0;
    if (expectedParity !== actualParity) {
      throw new Error(
        `Parity mismatch during decoding: landmark at x=${lm.x.toFixed(2)} (deltaX=${deltaX.toFixed(2)}) ` +
        `implies parity ${expectedParity}, but recovered pitch ${recoveredPitch} has parity ${actualParity}`
      );
    }

    return recoveredPitch;
  });
}

/**
 * Decode linear pitches for Round 37 intrinsically indexed symmetric cluster.
 * Reconstructs pitches strictly from the drawn anchor, reference divisions,
 * and sounding landmarks.
 */
export function decodeIndexedSymmetricCluster(
  baseLin: number,
  anchorStaffY: number,
  onsetX: number,
  divisions: readonly { offset: number; y: number; isOctave?: boolean }[],
  landmarks: readonly { y: number }[],
  u: number = HANDPRINT_PITCH_UNIT_U
): number[] {
  void onsetX;
  const divByOffset = new Map<number, number>();
  for (const d of divisions) {
    divByOffset.set(d.offset, d.y);
  }

  return landmarks.map((lm) => {
    const deltaY = anchorStaffY - lm.y;
    const semitonesFromBase = Math.round(deltaY / u);
    const recoveredPitch = baseLin + semitonesFromBase;

    // Verify alignment with intrinsic scale divisions:
    // Even offsets must align with a division level
    // Odd offsets must sit midway between division levels
    if (semitonesFromBase % 2 === 0) {
      const expectedY = anchorStaffY - u * semitonesFromBase;
      if (Math.abs(lm.y - expectedY) > 0.05) {
        throw new Error(
          `Even offset ${semitonesFromBase} does not sit at division level: y=${lm.y.toFixed(2)}, expected=${expectedY.toFixed(2)}`
        );
      }
    } else {
      const lowerDivY = anchorStaffY - u * (semitonesFromBase - 1);
      const upperDivY = anchorStaffY - u * (semitonesFromBase + 1);
      const midY = (lowerDivY + upperDivY) / 2;
      if (Math.abs(lm.y - midY) > 0.05) {
        throw new Error(
          `Odd offset ${semitonesFromBase} does not sit midway between divisions: y=${lm.y.toFixed(2)}, expected mid=${midY.toFixed(2)}`
        );
      }
    }

    return recoveredPitch;
  });
}

/**
 * Return discrete bounding boxes for all ink primitives that make up a cluster.
 */
export function getHandprintPrimitives(
  cluster: JankoHandprintCluster
): Array<[number, number, number, number]> {
  const boxes: Array<[number, number, number, number]> = [];
  const lms = cluster.landmarks;
  if (lms.length === 0) return boxes;

  if (cluster.presentation === 'indexed-symmetric') {
    const a = HANDPRINT_ROW_DISPLACEMENT_A;
    const reach = INDEXED_SYMMETRIC_LANDMARK_REACH;
    const onsetX = cluster.onsetX;

    // 1. Anchor numeral (or shared bass anchor region)
    if (!cluster.hasSharedAnchor) {
      boxes.push([
        onsetX - HANDPRINT_ORIGIN_KNOCKOUT_WX,
        cluster.anchorStaffY - HANDPRINT_ORIGIN_KNOCKOUT_HY,
        onsetX + HANDPRINT_ORIGIN_KNOCKOUT_WX,
        cluster.anchorStaffY + HANDPRINT_ORIGIN_KNOCKOUT_HY,
      ]);
    } else {
      boxes.push([
        onsetX - 2.53,
        cluster.anchorStaffY - 3.46,
        onsetX + 2.53,
        cluster.anchorStaffY + 3.46,
      ]);
    }

    // 2. Sounding landmark paired outward articulations
    for (const lm of lms) {
      // Left tick
      boxes.push([onsetX - a - reach, lm.y - 0.4, onsetX - a, lm.y + 0.4]);
      // Right tick
      boxes.push([onsetX + a, lm.y - 0.4, onsetX + a + reach, lm.y + 0.4]);
    }

    // 3. Scale reference divisions
    if (cluster.scaleDivisions) {
      for (const div of cluster.scaleDivisions) {
        const halfW = div.width / 2;
        boxes.push([onsetX - halfW, div.y - 0.3, onsetX + halfW, div.y + 0.3]);
      }
    }

    // 4. Slender body path segments
    for (let i = 0; i < lms.length - 1; i++) {
      boxes.push([
        onsetX - a - 0.3,
        Math.min(lms[i].y, lms[i + 1].y),
        onsetX + a + 0.3,
        Math.max(lms[i].y, lms[i + 1].y),
      ]);
    }

    // 5. Duration attachments
    if (cluster.durationRuns) {
      for (const run of cluster.durationRuns) {
        const firstLm = run.landmarks[0];
        const lastLm = run.landmarks[run.landmarks.length - 1];
        boxes.push([
          onsetX + a + reach,
          lastLm.y - 3.5,
          onsetX + a + reach + 9.0,
          firstLm.y + 3.5,
        ]);
      }
    }

    return boxes;
  }

  // 1. Origin knockout / digit box
  const origin = lms[0];
  boxes.push([
    origin.x - HANDPRINT_ORIGIN_KNOCKOUT_WX,
    origin.y - HANDPRINT_ORIGIN_KNOCKOUT_HY,
    origin.x + HANDPRINT_ORIGIN_KNOCKOUT_WX,
    origin.y + HANDPRINT_ORIGIN_KNOCKOUT_HY,
  ]);

  // 2. Landmark lobes
  for (const lm of lms) {
    if (lm.parity === 1) {
      boxes.push([
        lm.x - HANDPRINT_BODY_HALF_WIDTH,
        lm.y - HANDPRINT_LOBE_HALF_HEIGHT,
        lm.x + HANDPRINT_LOBE_WIDTH,
        lm.y + HANDPRINT_LOBE_HALF_HEIGHT,
      ]);
    } else {
      boxes.push([
        lm.x - HANDPRINT_LOBE_WIDTH,
        lm.y - HANDPRINT_LOBE_HALF_HEIGHT,
        lm.x + HANDPRINT_BODY_HALF_WIDTH,
        lm.y + HANDPRINT_LOBE_HALF_HEIGHT,
      ]);
    }
  }

  // 3. Connecting segments
  for (let i = 0; i < lms.length - 1; i++) {
    const yTop = lms[i + 1].y;
    const yBot = lms[i].y;
    const minX = Math.min(lms[i].x, lms[i + 1].x) - HANDPRINT_BODY_HALF_WIDTH;
    const maxX = Math.max(lms[i].x, lms[i + 1].x) + HANDPRINT_BODY_HALF_WIDTH;
    boxes.push([minX, yTop, maxX, yBot]);
  }

  // 4. Duration attachments
  if (cluster.isUniformRhythm && cluster.uniformDurationTicks !== undefined) {
    const topLm = lms[lms.length - 1];
    const stemY = topLm.y - HANDPRINT_LOBE_HALF_HEIGHT - 3.5;
    boxes.push([topLm.x - 3.5, stemY - 4.5, topLm.x + 3.5, topLm.y]);
  } else {
    for (const subset of cluster.durationSubsets) {
      const lm = subset.landmark;
      if (lm.parity === 1) {
        boxes.push([
          lm.x + HANDPRINT_LOBE_WIDTH,
          lm.y - 3.5,
          lm.x + HANDPRINT_LOBE_WIDTH + 8.5,
          lm.y + 3.5,
        ]);
      } else {
        boxes.push([
          lm.x - HANDPRINT_LOBE_WIDTH - 8.5,
          lm.y - 3.5,
          lm.x - HANDPRINT_LOBE_WIDTH,
          lm.y + 3.5,
        ]);
      }
    }
  }

  return boxes;
}

function boxIntersectsBox(
  b1: readonly [number, number, number, number],
  b2: readonly [number, number, number, number],
  clearance: number
): boolean {
  return (
    b1[0] - clearance <= b2[2] &&
    b1[2] + clearance >= b2[0] &&
    b1[1] - clearance <= b2[3] &&
    b1[3] + clearance >= b2[1]
  );
}

// ---------------------------------------------------------------------------
// Clearance Verification
// ---------------------------------------------------------------------------

/**
 * Check whether handprint cluster ink collides with barlines, noteheads, or rests.
 * Uses a broad-phase bounding-box test followed by a narrow-phase check against
 * actual ink primitives (origin knockout, landmark lobes/articulations, connecting segments,
 * scale divisions, and duration attachment cues).
 */
export function checkHandprintCollisions(
  cluster: JankoHandprintCluster,
  barlineXs: readonly number[],
  independentNotes: readonly PositionedJankoNote[],
  rests: readonly any[],
  minClearance: number = 1.0
): { collides: boolean; obstacle?: string; details?: string } {
  const [minX, minY, maxX, maxY] = cluster.inkBox;
  const primitives = getHandprintPrimitives(cluster);

  // 1. Check barlines
  for (const bx of barlineXs) {
    if (bx >= minX - minClearance && bx <= maxX + minClearance) {
      for (const prim of primitives) {
        if (bx >= prim[0] - minClearance && bx <= prim[2] + minClearance) {
          return {
            collides: true,
            obstacle: 'barline',
            details: `Cluster ink touches barline at x=${bx.toFixed(1)}`,
          };
        }
      }
    }
  }

  // 2. Check independent noteheads (other hand or different onset)
  for (const n of independentNotes) {
    const noteId = n.note?.id ?? (n as any).id;
    if (cluster.allNoteIds.has(noteId)) continue;
    // Shared bass anchor is reused and intentionally co-located, not an obstacle
    if (cluster.hasSharedAnchor && cluster.sharedBassSurvivorId && noteId === cluster.sharedBassSurvivorId) continue;
    const nx = n.x;
    const ny = n.y;
    if (nx === undefined || ny === undefined) continue;
    const wx = 2.53;
    const hy = 3.46;
    const noteBox: [number, number, number, number] = [nx - wx, ny - hy, nx + wx, ny + hy];
    const nStartTick = n.note?.startTick ?? (n as any).startTick;
    const requiredClearance = nStartTick === cluster.startTick ? 0 : minClearance;

    // Broad phase
    if (!boxIntersectsBox(cluster.inkBox, noteBox, requiredClearance)) continue;

    // Narrow phase
    for (const prim of primitives) {
      if (boxIntersectsBox(prim, noteBox, requiredClearance)) {
        return {
          collides: true,
          obstacle: 'notehead',
          details: `Cluster ink touches notehead ${noteId} at (${nx.toFixed(1)}, ${ny.toFixed(1)})`,
        };
      }
    }
  }

  // 3. Check rests
  for (const r of rests) {
    if (r && typeof r.x === 'number' && typeof r.y === 'number') {
      const rx = r.x;
      const ry = r.y;
      const rw = 4.0;
      const rh = 6.0;
      const restBox: [number, number, number, number] = [rx - rw, ry - rh, rx + rw, ry + rh];

      // Broad phase
      if (!boxIntersectsBox(cluster.inkBox, restBox, minClearance)) continue;

      // Narrow phase
      for (const prim of primitives) {
        if (boxIntersectsBox(prim, restBox, minClearance)) {
          return {
            collides: true,
            obstacle: 'rest',
            details: `Cluster ink touches rest at (${rx.toFixed(1)}, ${ry.toFixed(1)})`,
          };
        }
      }
    }
  }

  return { collides: false };
}
